Capstone Project
cyrilmuchemi/Capstone-Project pull request #1
Opened 2022-04-15 14:29 UTC by cyrilmuchemi

- This capstone project is about an African Summit.
- It has two pages, about.html and index.html.
- It is a simple website.

2022-04-15 20:11 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @cyrilmuchemi,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * Your design matches the template design. :heavy_check_mark:
> * Github flow is used :heavy_check_mark:.
> * Colors and fonts are correct :heavy_check_mark:.
> 
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding!:clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-15 20:11 UTC, topeogunleye commented on dynamic.js
> +for (let i = 0; i < speakers.length; i += 1) {
- [ ] [REQUIRED] I kindly suggest that you wrap your for loop in a `windows.onload` function so that your script runs once your web page has completely loaded all content **e.g** 

```
window.onload = () => {
for (let i = 0; i < speakers.length; i += 1) {
    speakerSection.innerHTML += ` 
  <div class="individual">
  <div class="myImage">
      <img src= '${speakers[i].image}'>
  </div>
  <div class="description">
      <h2>${speakers[i].name}</h2>
      <h3>${speakers[i].occupation}</h3>
      <p>${speakers[i].description} </p>
  </div>
</div>
  `;
} `
```

2022-04-15 22:58 UTC, cyrilmuchemi commented on desktop.css
> +    flex-direction: column;
@topeogunleye they are aligned using grid auto

2022-04-16 01:13 UTC, codepantha approved these changes
Hi @cyrilmuchemi 👋, 

## STATUS: APPROVED ✔️ 
Great job implementing all the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Since the previous reviewer didn't point this out, this is optional but advisable. Kindly fix the horizontal scrolling on the desktop and mobile view shown below 👇 
![image](https://user-images.githubusercontent.com/46839548/163655996-f6f95a50-1468-411b-a6b6-eb1b8d5ea126.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-16 05:56 UTC, merged

2022-04-16 06:15 UTC, topeogunleye commented on desktop.css
> +    flex-direction: column;
You can align them with CSS grid or flexbox but they need to be horizontal on desktop